---
- name: Add User
  hosts: all
  tasks:
    - name: Install package
      when: ansible_os_family == "Redhat"
      user:
        name: "{{ item }}"
      with_items:
          - bob
          - ben
          - lilia
          - lisa
          - bryan
          - oliver
